ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "doubledot"
  site-url: "https://josephsmann.github.io/doubledot"
  description: "running out of steam"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/josephsmann/doubledot"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/josephsmann/doubledot"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
