# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/doubledot',
                'doc_host': 'https://josephsmann.github.io',
                'git_url': 'https://github.com/josephsmann/doubledot',
                'lib_path': 'doubledot'},
  'syms': {'doubledot.core': {'doubledot.core.foo': ('core.html#foo', 'doubledot/core.py')}}}