# AUTOGENERATED! DO NOT EDIT! File to edit: ../small_tests.ipynb.

# %% auto 0
__all__ = []

# %% ../small_tests.ipynb 4
import doubledot.ATMS_api as atms
import doubledot.crema_sf as SF
import jmespath as jp
import json
import pandas as pd
from nbdev.showdoc import *
